### ISSUE TITLE
If a remote copy link already exists, the IP validation is ignored. 

### ISSUE THREAD

**Issue by farhan7500** [HewlettPackard/hpe3par_ansible_module#11]
[Details here](https://github.com/farhan7500/hpe3par_ansible_module/issues/9)

**Comment by ansarars** [comment]
fixed in PR https://github.com/farhan7500/python-3parclient/pull/4

**Comment by leenaj0hn** [comment]
Verified issue, message should be formatted correctly
**""msg": "Admit remote copy link failed | I,n,v,a,l,i,d, ,I,P,v,4, ,a,d,d,r,e,s,s,:, ,1,9,2,.,1,6,8,.,1,.,"**

**Comment by ansarars** [comment]
Issue is fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/1
Note: Above PR is in review

**Comment by leenaj0hn** [comment]
Message format issue resolved. Mark issue for closing
