### ISSUE TITLE
Schedule tasks fail when retention time is set greater than expiration time

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#15]

**Comment by leenaj0hn** [comment]
**The playbook sets the retention time greater than expiration time**

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": 2,
            "expiration_unit": "Days",
            "new_name": null,
            "priority": null,
            "**read_only": true,
            "retention_hours": 0,
            "retention_time": 3,
            "retention_unit": "Days",**
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "50 * * * *"
        }
    },
    "msg": "Created Schedule Ansible_schedule_01 successfully."


**On 3par array:**

SchedName           File/Command                                                                                        Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
Ansible_schedule_01 createsv -ro -exp 48h -retain 72h snap-Ansible_volume_SS_01.@y@@m@@d@@H@@M@@S@ Ansible_volume_SS_01  50    *   *     *   * 3paradm   active     Y 2018-10-10 11:50:00 IST
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1                   total

CSSOS-SSA06 cli% showtask
   Id Type           Name                Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
22400 scheduled_task Ansible_schedule_01 **failed**   ---  --- 2018-10-10 11:50:00 IST 2018-10-10 11:50:00 IST n/a        3paradm

**Comment by nirupaman** [comment]
Fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by farhan7500** [comment]
@leenaj0hn Please could you verify and close?

**Comment by leenaj0hn** [comment]
Verified and closing the issue
