### ISSUE TITLE
Create schedule tasks should not fails if user does not set retention time and unit parameters

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#16]
In properties file do not set retention time and unit. The retention time defaults to 0, but the create schedule task fails with the below error. Since the user has to set either expiration or retention time or both, the task should not fails if either is not set.

**Playbook**
storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: schedule_create
schedule_name: "Ansible_schedule_01"
snapshot_name: "Ansible_volume_SS_snap_01"
base_volume_name: "Ansible_volume_SS_01"
read_only: true
expiration_time: 2
expiration_unit: "days"
**retention_time:
retention_unit:
t**ask_freq_custom: "0 8-17 * * *"

**Task error**
    "invocation": {
        "module_args": {
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": 2,
            "expiration_unit": "days",
            "read_only": true,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq_custom": "0 8-17 * * *"
        }
    },
    **"msg": "value of retention_unit must be one of: Hours, Days, got: None"**

**Comment by farhan7500** [comment]
Not a defect.

Since no value is provided against the retention_unit, it does not match with the expected choices. Hence the failure. It is the expected result.

**Comment by leenaj0hn** [comment]
Closing this issue
