### ISSUE TITLE
Create snapshot scheduled fails as schedule name exceeds 32 characters

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#17]
**If schedule name exceeds 20 characters, the schedule fails to trigger with below error:**

CSSOS-SSA06 cli% showtask -d 22409
   Id Type           Name                Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
22409 scheduled_task Ansible_schedule_01 **failed**   ---  --- 2018-10-10 15:20:00 IST 2018-10-10 15:20:01 IST n/a        3paradm

Detailed status:
2018-10-10 15:20:00 IST Created     task.
2018-10-10 15:20:00 IST Updated     Executing "Ansible_schedule_01" as 0:14172
**2018-10-10 15:20:01 IST Error       Name snap-Ansible_volume_SS_01.181010152001 is too long, should be less than 32 characters**
2018-10-10 15:20:01 IST Error       Task exited with status 1
2018-10-10 15:20:01 IST Failed      Could not complete task.

**Playbook properties:**
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": 2,
            "expiration_unit": "Hours",
            "new_name": null,
            "priority": null,
            "read_only": true,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "20 * * * *"
        }
    },
    "msg": "Created Schedule Ansible_schedule_01 successfully."

**Comment by nirupaman** [comment]
Fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by nirupaman** [comment]
As discussed i am creating schedule for snapshot with snapshot name as base_volume_name dot timestamp. I have added check to limit the length of snapshot name to be between 1 - 19

**Comment by leenaj0hn** [comment]
As discussed the snapshot name includes the base_vol_name.timestamp. The base vol name will be restricted to less than 19 characters, which will be documented
Verified this issue. Closing the issue
