### ISSUE TITLE
Snapshot name in schedule incorrect 

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#18]
Currently the snapshot schedule name pre appends the base_vol_name with a fixed string:
Example pasted below:
snap-Ansible_volume_SS_01.@y@@m@@d@@H@@M@@S@ Ansible_volume_SS_01

The snapshot name format should append the snapshot name from the properties file and append timestamp mentioned in schedule.

**Comment by nirupaman** [comment]
In progress

**Comment by farhan7500** [comment]
@leenaj0hn Please could you verify the fix?

**Comment by leenaj0hn** [comment]
As discussed the snapshot name includes the base_vol_name.timestamp.
Verified this issue. Closing the issue
