### ISSUE TITLE
User should not be forced to set both task_freq, and task_freq_custom

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#20]
When the task_freq property is not set and task_freq_custom is set, the below error is seen

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "base_volume_name": "An_vol_SS_01",
            "expiration_hours": 0,
            "expiration_time": 2,
            "expiration_unit": "Hours",
            "read_only": true,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "create_schedule",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "0 8-72 * * *"
        }
    },
    "msg": "value of task_freq must be one of: yearly, monthly, weekly, daily, hourly, got: None"

**Comment by nirupaman** [comment]
removed task_freq_custom there will be now only one option task_freq to set task frequency.
Fixed https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by leenaj0hn** [comment]
Closing this issue.
