### ISSUE TITLE
admit rcopy link fails with not relevant error message when source and target IP is the same

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#23]
admit rcopy link fails with not relevant error message when source and target IP is the same

**Comment by ansarars** [comment]
Issue is fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/1
Note: PR is in review

**Comment by leenaj0hn** [comment]
Verified Issue. Marking as closed
