### ISSUE TITLE
admit volume to remote copy link fails when 'differentSecondaryWWN' field value is set to true.

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#25]
Properties file

storage_system_ip: "192.168.67.7"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
remote_copy_group_name: "ansible_CreateRCG-002"
state: add_volume
volume_name: "Ansible_volume_01"
admit_volume_targets:
 - target_name: "CSSOS-SSA05"
   sec_volume_name: "Sec_vol_1"
snapshot_name:
**volume_auto_creation: true**
skip_initial_sync: true
**different_secondary_wwn: true**

**Error**

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admit_volume_targets": [
                {
                    "sec_volume_name": "Sec_vol_1",
                    "target_name": "CSSOS-SSA05"
                }
            ],
            "different_secondary_wwn": true,
            "discard_new_data": false,
            "domain": null,
            "full_sync": false,
            "keep_snap": false,
            "local_groups_direction": false,
            "local_remote_volume_pair_list": null,
            "local_snap_cpg": null,
            "local_user_cpg": null,
            "modify_targets": null,
            "no_resync_snapshot": false,
            "no_snapshot": false,
            "recovery_action": null,
            "remote_copy_group_name": "ansible_CreateRCG-002",
            "remote_copy_targets": null,
            "remove_secondary_volume": false,
            **"skip_initial_sync": true,**
            "skip_promote": false,
            "skip_start": false,
            "skip_sync": false,
            "snapshot_name": null,
            "source_port": null,
            "starting_snapshots": null,
            "state": "add_volume",
            "stop_groups": false,
            "storage_system_ip": "192.168.67.7",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "target_mode": null,
            "target_name": null,
            "target_port_wwn_or_ip": null,
            "unset_snap_cpg": false,
            "unset_user_cpg": false,
            "volume_auto_creation": true,
            "volume_name": "Ansible_volume_01"
        }
    },
    **"msg": "Add volume to Remote Copy Group failed. skipInitialSync cannot be true if snapshot name is not given"**
}

**Comment by ansarars** [comment]
This issue is fixed in PR (https://github.com/HewlettPackard/hpe3par_ansible_module/pull/28)

**Comment by leenaj0hn** [comment]
Verified the issue. closing the defect.
