### ISSUE TITLE
On trying to resume a schedule which is not in 'suspended' state, and invalid error msg is displayed

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#30]
On trying to resume a schedule which is not in 'suspended' state, and invalid error msg is displayed. 

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": null,
            "expiration_hours": 0,
            "expiration_time": null,
            "expiration_unit": "Hours",
            "new_name": null,
            "new_schedule_name": null,
            "priority": null,
            "read_only": null,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": null,
            "state": "resume_schedule",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null
        }
    },
    **"msg": "Schedule resumed failed | An unknown exception occurred."**

**Comment by ansarars** [comment]
Issue is fixed in below PRs:-
https://github.com/HewlettPackard/hpe3par_python_sdk/pull/16
https://github.com/HewlettPackard/hpe3par_ansible_module/pull/32
https://github.com/hpe-storage/python-3parclient/pull/54

**Comment by leenaj0hn** [comment]
Issue verified, closing this bug
