### ISSUE TITLE
Unable to perform create RCG link operations

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#35]
Getting error as "unsupported operation for the resource" while creating RCG link on array 3.2.2(MU6).

Steps to reproduce:-

property file:
storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: present
remote_copy_group_name: "ansible_CreateRCG-001"
#target_name: "CSSOS-SSA05"
#target_mode: "periodic"
domain:
remote_copy_targets:
# - target_name: "CSSOS-SSA05"
 - target_name: "CSSOS-SSA04"
   target_mode: "periodic"
# - userCPG:
# - snapCPG:
keep_snap: "1"
local_user_cpg:
local_snap_cpg:

Task:
---
    - name: Create RCG
      hpe3par_remote_copy:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=present
        remote_copy_group_name="{{ remote_copy_group_name }}"
        domain="{{ domain }}"
        remote_copy_targets="{{ remote_copy_targets }}"
        local_user_cpg="{{ local_user_cpg }}"
        local_snap_cpg="{{ local_snap_cpg }}"

Please find attached testing log for reference.
[create_RCG_link_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2622937/create_RCG_link_issue.txt)

**Comment by ansarars** [comment]
Sent gerrit review  https://gerrit.storage.hpecorp.net:8081/#/c/63284/  for this fix

**Comment by virendra-sharma** [comment]
Able to admit RCG link.

Please find attached verification log.
[verified_admit_RCG_link_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2639090/verified_admit_RCG_link_issue.txt)
