### ISSUE TITLE
Admit taget in RCG with wrong RCG name giving error message in green and passing TC

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#36]
While adding target to RCG with incorrect RCG name gives error message in green and passing TC as successful, whereas failure expected.

Steps to re-produce:-

Property file to add RCG:

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: present
remote_copy_group_name: "ans_CreateRCG_t-001"
domain:
#target_name: "CSSOS-SSA05"
remote_copy_targets:
 - target_name: "CSSOS-SSA05"
# - target_name: "CSSOS-SSA06"
   target_mode: "periodic"
# - userCPG:
# - snapCPG:
keep_snap: "false"
local_user_cpg:
local_snap_cpg:

Property file to add target:

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
remote_copy_group_name: "ansible_CreateRCG_target-001"
state: admit_target
target_mode: "sync"
target_name: "CSSOS-SSA04"
local_remote_volume_pair_list:

Please find attached test log for the same.
[Admit_RCG_target_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2623162/Admit_RCG_target_issue.txt)

**Comment by sneharai4** [comment]
@ansarars  This is a valid bug. We need to fix this.

**Comment by farhan7500** [comment]
Fixed

**Comment by sneharai4** [comment]
Fixed in https://github.com/HewlettPackard/hpe3par_ansible_module/pull/42

**Comment by sneharai4** [comment]
@virendra-sharma  Please verify

**Comment by virendra-sharma** [comment]
Error messaged corrected and TC failing as expected.

Please find attached verified testing log.
[verified_invalid_RCG_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2639045/verified_invalid_RCG_issue.txt)
