### ISSUE TITLE
Delete remote copy which do not exist, giving wrong error message and passing TC.

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#37]
While deleting RCG which do not exist, getting error message as "Remote Copy Group is already present" and it is passing TC as successful.

Steps to Reproduce:-

Property file:-

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: present
remote_copy_group_name: "ansible_CreateRCG-001"
#target_name: "CSSOS-SSA05"
#target_mode: "periodic"
domain:
remote_copy_targets:
# - target_name: "CSSOS-SSA05"
 - target_name: "CSSOS-SSA04"
   target_mode: "periodic"
# - userCPG:
# - snapCPG:
keep_snap: "1"
local_user_cpg:
local_snap_cpg:

Task :-

---
    - name: Delete remote copy group "{{ remote_copy_group_name }}"
      hpe3par_remote_copy:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent
        remote_copy_group_name="{{ remote_copy_group_name }}"
        keep_snap="{{ keep_snap }}"
      tags:
       - createremotecopy

Please find attached test result logs.
[Delete_RCG_which_not_exist_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2623233/Delete_RCG_which_not_exist_issue.txt)

**Comment by sneharai4** [comment]
@virendra-sharma No details in the attached log file. It has only the playbook name.

**Comment by sneharai4** [comment]
Fixed in https://github.com/HewlettPackard/hpe3par_ansible_module/pull/42

**Comment by sneharai4** [comment]
@virendra-sharma  Please verify.
