### ISSUE TITLE
Unable to create scheduling without retention value & unit

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#38]
I am unable to create schedule without retension unit & value, please find below details.

Property file:

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: create_schedule
schedule_name: "Ansible_schedule_01"
#snapshot_name: "Ansible_volume_SS_snap_01"
base_volume_name: "An_vol_SS_01"
read_only:
expiration_time: 2
expiration_unit: Hours
#task_freq_custom: "8 * * * *"
task_freq: "8 * * * *"

task file:

---
    - name: Create schedule
      hpe3par_snapshot:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=create_schedule
        schedule_name="{{ schedule_name }}"
        base_volume_name="{{ base_volume_name }}"
        read_only="{{ read_only }}"
        expiration_time="{{ expiration_time }}"
        expiration_unit="{{ expiration_unit }}"
        task_freq="{{ task_freq }}"

playbook;

---
- hosts: localhost
  tasks:

    - name: 'CREATERCG:TS01, Create a volume and snapshot'

      include_vars: 'properties/create_schedule_ts02_properties.yml'

    - import_tasks: 'tasks/create_vv_playbook.yml'

    - name: 'Create a schedule to trigger every hour'
      include_vars: 'properties/create_schedule_ts01_properties.yml'

    - import_tasks: 'tasks/create_schedule_playbook.yml'

    - pause:
          prompt: "Press Enter"

    - import_tasks: 'tasks/delete_schedule_playbook.yml'

Please find attached test log.
[scheduling_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2627758/scheduling_issue.txt)

**Comment by farhan7500** [comment]
- Fixed a related issue where the exp and ret hours values were both 0
- Need to run the exact playbook to reproduce this issue

**Comment by sneharai4** [comment]
Fixed in https://github.com/HewlettPackard/hpe3par_ansible_module/pull/41

**Comment by sneharai4** [comment]
@virendra-sharma Please verify.

**Comment by virendra-sharma** [comment]
Schedule created without passing retention value and taking default value as 0 & Null if retention mentioned in task.

Pplease find attached testing log for verification.
[verified_schedule_retension_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2639129/verified_schedule_retension_issue.txt)
