### ISSUE TITLE
Modifying non existing schedule, getting error message in green and TC passed successful

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#39]
While modifying non existing schedule getting error message in green and TC passing, where as failure expected.

Please find attached log for the same.
[non_existing_schedule_modify_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2628915/non_existing_schedule_modify_issue.txt)

**Comment by sneharai4** [comment]
PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/40

**Comment by sneharai4** [comment]
@virendra-sharma Please verify.

**Comment by virendra-sharma** [comment]
Error message comes in green and TC passing as expected.

please find attached updated log.
[verified_modify_schedule_non_existing_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2639191/verified_modify_schedule_non_existing_issue.txt)
