### ISSUE TITLE
Admit RCG target worked successful without RCG link between source & target array.

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#43]
I tried to admit RCG target to array which was not linked to source array, expected result was failure and proper message regarding no existing link but TC passed successful with message "Admit target successful".

Dismiss link:-
CSSOS-SSA06 cli% dismissrcopylink CSSOS-SSA04 1:3:1:10.100.3.26

Property file to add RCG & tagret :-

---
- hosts: localhost
  tasks:

    - name: 'Create rcg and admit remote copy target with valid RCG name'
      include_vars: 'properties/admit_rcg_target_ts02_properties.yml'

    - import_tasks: 'tasks/create_remote_copy_group_playbook.yml'

    - name: 'Admit target'
      include_vars: 'properties/admit_rcg_target_ts04_properties.yml'
    - import_tasks: 'tasks/admit_remote_copy_target_playbook.yml'

properties/admit_rcg_target_ts02_properties.yml :-

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: present
remote_copy_group_name: "ans_CreateRCG_t-001"
domain:
#target_name: "CSSOS-SSA05"
remote_copy_targets:
 - target_name: "CSSOS-SSA05"
# - target_name: "CSSOS-SSA06"
   target_mode: "periodic"
# - userCPG:
# - snapCPG:
keep_snap: false
local_user_cpg:
local_snap_cpg:

properties/admit_rcg_target_ts04_properties.yml :=

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
remote_copy_group_name: "ans_CreateRCG_t-001"
state: admit_target
target_mode: "sync"
target_name: "CSSOS-SSA04"
local_remote_volume_pair_list:

Please find attached log of testing.
[admit_target_without_link_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2632869/admit_target_without_link_issue.txt)

**Comment by ansarars** [comment]
Fixed the issue in PR(https://gerrit.storage.hpecorp.net:8081/#/c/63305/)
Note: Review is in progress

**Comment by sneharai4** [comment]
@virendra-sharma @leenaj0hn Please verify. Latest code is in master of python-client

**Comment by virendra-sharma** [comment]
TC getting failed as expected, if not link present but trying to add target.
However error message is not justifying exact cause of problem, Dev team suggested it is coming from CLI so can't modify it, hence closing this bug as fixed.
[Verified_admit_target_without_rcg_link_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2651832/Verified_admit_target_without_rcg_link_issue.txt)
