### ISSUE TITLE
Error message not justifying exact cause of failure, in case of invalid target during RCG creation.

### ISSUE THREAD

**Issue by virendra-sharma** [HewlettPackard/hpe3par_ansible_module#48]
While creating RCG given invalid RCG name, error states "pecified target is not a target of remote copy group", which do not specify exact problem.

3PAR error states := "Could not find target CSSOS-SSA"

Please fine below log for the same.

property file:=

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: present
remote_copy_group_name: "ansible_CreateRCG-003"
domain: "test_domain"
remote_copy_targets:
 - target_name: "InvalidTargetName"
   target_mode: "sync"
   user_cpg:
   snap_cpg:
local_user_cpg:
local_snap_cpg:
keep_snap: false

Please attach log for the same.
[invalid_rcg_error_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2633168/invalid_rcg_error_issue.txt)

**Comment by farhan7500** [comment]
Arshad to fix the error message

**Comment by ansarars** [comment]
@virendra-sharma We are using wsapi for remote copy group creation and it is returning below error message in response in case of invalid target name:-
    "code": 194,
    "desc": "specified target is not a target of remote copy group" 

Hence no need to fix it

Please close this bug

**Comment by virendra-sharma** [comment]
Reviewed same error message in WSAPI and as expected behaviour, error message will be same as WSAPI so it's achieved.

Recommended to handle error messages user friendly, which can be enhance in future.
