### ISSUE TITLE
Create schedule tasks displays as successful, when base volume is not present on the array

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#5]
1. In create schedule playbook, enter the a volume(snap and base volume) name that does not exist on the array. The "create schedule" tasks displays as successful.

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": null,
            "expiration_unit": "Hours",
            "new_name": null,
            "priority": null,
            "read_only": null,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.5",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "0 * * * *"
        }
    },
    **"msg": "Created Schedule Ansible_schedule_01 successfully."**

On the array the "showsched" cmd does not display the schedule 
**CSSOS-SSA06 cli% showsched
No scheduled tasks listed**

**Comment by nirupaman** [comment]
Fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by leenaj0hn** [comment]
Verified, closing this issue
