### ISSUE TITLE
Time range validation missing for sync period and snap frequency values while modify an rcg

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#50]
The valid range for sync period and snap frequency values are between 300 - 31622400 seconds ( one year ). If the user provides an invalid range eg: 51622400 the playbook passes with no errors.

**Comment by ansarars** [comment]
Sent review request for this fix in PR (https://gerrit.storage.hpecorp.net:8081/#/c/63343/)

**Comment by sneharai4** [comment]
Fixed in https://github.com/HewlettPackard/hpe3par_ansible_module/pull/51

**Comment by virendra-sharma** [comment]
Verified with valid/invalid snap period combination and it is working fine on array 3.2.2.
Please find attached testing log for invalid snap period input.
[verified_invalid_snap_period_issue.txt](https://github.com/HewlettPackard/hpe3par_ansible_module/files/2653009/verified_invalid_snap_period_issue.txt)

**Comment by leenaj0hn** [comment]
Verified issue on latest build. Issue is resolved, closing the same
