### ISSUE TITLE
Create schedule fails when "readonly" value is not specified in properties file

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#6]
In the create schedule properties file, the readonly value is blank.

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: schedule_create
schedule_name: "Ansible_schedule_01"
snapshot_name: "Ansible_volume_SS_snap_01"
base_volume_name: "Ansible_volume_SS_01"
**read_only:**
expiration_time: 2
expiration_unit: "Hours"
task_freq_custom: "0 * * * *"

**The create schedule tasks displays as successful:** 
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": null,
            "expiration_unit": "Hours",
            "new_name": null,
            "priority": null,
            "read_only": null,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "0 * * * *"
        }
    },
    **"msg": "Created Schedule Ansible_schedule_01 successfully."**
}

The array does not list the schedule
**CSSOS-SSA06 cli% showsched
No scheduled tasks listed**

"createsv" command help mentions that if the "readonly" property value is not specified, the default value should be set to "read/write"

**OPTIONS
    -ro
        Specifies that the copied volume is read-only. If not specified, the
        volume is read/write.**

**Comment by leenaj0hn** [comment]
This issue is the same when user sets the readonly property value to "false"

playbook:
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "An_vol_SS_01",
            "expiration_hours": 0,
            "expiration_time": 2,
            "expiration_unit": "Hours",
            "new_name": null,
            "priority": null,
            **"read_only": false,**
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "50 * * * *"
        }
    },
    "msg": "Created Schedule Ansible_schedule_01 successfully."
}

**Comment by nirupaman** [comment]
Fixed https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by nirupaman** [comment]
Invalid.
It will create schedule with read write snapshot

CSSOS-SSA04 cli% showsched
                                                                                                                                            ------ Schedule ------                                                                                        
SchedName     File/Command                                                                                                                  Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime                                                     
my_ansible_sc createsv -exp 3h -retain 3h volume_ansible_a.@y@@m@@d@@H@@M@@S@ vo                                             lume_ansible_a   0    *   *     *   * 3paradm   active     Y 2018-10-12 13:00:00                                              IST

**Comment by nirupaman** [comment]
Fixed 
CSSOS-SSA04 cli% showsched
------ Schedule ------
SchedName File/Command Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
my_ansible_sc createsv -exp 3h -retain 3h volume_ansible_a.@y@@m@@d@@h@@m@@s@ vo lume_ansible_a 0 * * * * 3paradm active Y 2018-10-12 13:00:00 IST
