### ISSUE TITLE
Create schedule fails when invalid number of task schedule parameters (task_freq_custom) are set in the properties file

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#7]
Create a property file in valid number of "Min, hour, DOM, Month and DOW" in (task_freq_custom) field in the property file

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: schedule_create
schedule_name: "Ansible_schedule_01"
snapshot_name: "Ansible_volume_SS_snap_01"
base_volume_name: "Ansible_volume_SS_01"
read_only: true
expiration_time: 2
expiration_unit: "Hours"
**task_freq_custom: "1  * * *"**

**The playbook task displays as successful completion on create schedule task** 

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": null,
            "expiration_unit": "Hours",
            "new_name": null,
            "priority": null,
            "read_only": true,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "1  * * *"
        }
    },
    "msg": "Created Schedule Ansible_schedule_01 successfully."
}

**The array shows no schedules created**

**CSSOS-SSA06 cli% showsched
No scheduled tasks listed**

**Comment by nirupaman** [comment]
Fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by leenaj0hn** [comment]
Verified, closing this issue
