### ISSUE TITLE
Create schedule fails when and invalid range is passed in "task_freq_custom" field

### ISSUE THREAD

**Issue by leenaj0hn** [HewlettPackard/hpe3par_ansible_module#9]
**Create a playbook with the hours range exceeding 24 hrs.** 

storage_system_ip: "192.168.67.6"
storage_system_username: "3paradm"
storage_system_password: "3pardata"
state: schedule_create
schedule_name: "Ansible_schedule_01"
snapshot_name: "Ansible_volume_SS_snap_01"
base_volume_name: "Ansible_volume_SS_01"
read_only: true
expiration_time: 2
expiration_unit: "Hours"
**task_freq_custom: "0 8-72 * * *"**

**The create playbook displays as successful**
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "allow_remote_copy_parent": null,
            "base_volume_name": "Ansible_volume_SS_01",
            "expiration_hours": 0,
            "expiration_time": null,
            "expiration_unit": "Hours",
            "new_name": null,
            "priority": null,
            "read_only": true,
            "retention_hours": 0,
            "retention_time": null,
            "retention_unit": "Hours",
            "rm_exp_time": null,
            "schedule_name": "Ansible_schedule_01",
            "snapshot_name": "Ansible_volume_SS_snap_01",
            "state": "schedule_create",
            "storage_system_ip": "192.168.67.6",
            "storage_system_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "storage_system_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "task_freq": null,
            "task_freq_custom": "0 8-72 * * *"
        }
    },
    **"msg": "Created Schedule Ansible_schedule_01 successfully."**

**The 3par "showsched" output list no schedules**
**CSSOS-SSA06 cli% showsched
No scheduled tasks listed**

**Comment by nirupaman** [comment]
Fixed in PR https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by leenaj0hn** [comment]
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_dmP_jv/ansible_module_hpe3par_snapshot.py\", line 788, in <module>\n    main()\n  File \"/tmp/ansible_dmP_jv/ansible_module_hpe3par_snapshot.py\", line 771, in main\n    schedule_name, base_volume_name, read_only, expiration_time, retention_time, expiration_unit, retention_unit, task_freq, task_freq_custom)\n  File \"/tmp/ansible_dmP_jv/ansible_module_hpe3par_snapshot.py\", line 528, in create_schedule\n    if (int(hour_task) > 23 or int(hour_task) < 0):\nValueError: invalid literal for int() with base 10: '8-72'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}


The above error is seen when a list (range) is specified as input in "task_freq_custom" field

**Comment by nirupaman** [comment]
I think you have taken older changes

**Comment by nirupaman** [comment]
Please take the latest code https://github.com/HewlettPackard/hpe3par_ansible_module/pull/8

**Comment by leenaj0hn** [comment]
Closing this issue. Task_freq_custom field is removed
